name := "My Project"
version := "1.0"
scalaVersion := "2.11.7"
libraryDependencies += "com.typesafe.akka" % "akka-actor_2.11" % "2.3.4"
resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"